### ISSUE TITLE
Crash in 2.1.0 when trying to edit MMC instance.

### ISSUE THREAD

**Issue by xannor** [joonatoona/OpenMineMods#37]
I tried to click on edit on my MMC instance in the list to try and update it, and I got an index out of range crash report. I don;t know where the app sends them, but if you do not get them I can try to capture it and put it in a gist.

**Comment by notjuliee** [comment]
The crash reports get sent off to my server, it should have given you a UUID. The latest one was an index out of range, so that's probably yours.

So it looks like there's no versions of that mod for your instance version. That's probably because it's a minor version off, for example it says it's for `1.10.2` but you're using `1.10.1`. I've fixed it so it won't crash, but those mods won't be updated automatically.
